### ISSUE TITLE
Any ideas on how to reuse the compilation time container in runtime?

### ISSUE THREAD

**Issue by kkppll-ss** [swaechter/jooq-gradle-testcontainer-flyway-example#1]
Hi Simon,

Thank you so much for this great example! I am working on a project which uses Jooq + flyway + testcontainers + Gradle and cannot figure out how to configure it properly. Glad I see your example!

However, it seems that you are using two different containers for jooq generation and for running the tests. That is because the container used for jooq generation is thrown away after jooq completes. Do you have any ideas about how to reuse the same container to run the tests?

**Comment by swaechter** [comment]
Hey really glad to hear that my example helped you :) You're right that two Testcontainer instances are used:

* The first one during `code generation`/before the `compile` task
* The second during the `test` task

So to overcome this issue you would have to start a container **before** the `code generation`/`compile` task and stop it **after** the `test` task. At the moment I don't know how to do this, but I have two ideas:

1. Try to script this in the Gradle build script
2. Try to implement a custom Gradle plugin where the `code generation`/`compile` tasks depend on a custom task that starts the Testcontainer and an afterwards-task that is executed after `test` to shutdown the container

Both solutions would mean you have to used a fixed port/fixed credentials to keep the setup simple (Or pass down the dynamic port e.g. via environment variables). I am not aware of a quick example how to accomplish this - sorry I can't share any code.

On the other hand: Do two container instances really hurt your developer experience? I don't change my DB layout that often, so the first Testcontainer instance isn't run at all (Cached away as long `src/main/resources/db/migration` doesn't change). Only the second instance is used for tests. Doesn't this work out for you?

Best,
Simon

**Comment by kkppll-ss** [comment]
Yes reusing testcontainers is really hard:) I tried to implement it but I quickly get a lot of problems.

Here is an example Jooq configuration snippet from https://github.com/etiennestuder/gradle-jooq-plugin#gradle-groovy-dsl-4.

```groovy
                jdbc {
                    driver = 'org.postgresql.Driver'
                    url = 'jdbc:postgresql://localhost:5432/sample'
                    user = 'some_user'
                    password = 'some_secret'
                    properties {
                        property {
                            key = 'ssl'
                            value = 'true'
                        }
                    }
                }
```

The main problem is that I cannot find a way to replace 'jdbc:postgresql://localhost:5432/sample' with one that is dynamically generated from a Gradle task -- testcontainers use random ports. One way is to write all the code to start testcontainers in Gradle `build.gradle` (instead of putting them into some tasks), but this gives me another problem that the container will always be started regardless of which task I run -- even if I run a `gradle clean`. 

I initially think that not passing testcontainers into runtime will give me some problems, like it might make the CI slower since I have to run migration twice. However, it turns out not to be a major issue. It actually gives me an advantage that the runtime database is decoupled from the build time database -- I can use a local database to develop, a testcontainers container to test, or a remote database running at AWS for production, while jooq generation is always performed by testcontainers.

Thank you for much for sharing the code!
